#!/usr/bin/expect -f
#trap sigwinch spawned
trap {
 set rows [stty rows]
 set cols [stty columns]
 stty rows $rows columns $cols < $spawn_out(slave,name)
} WINCH
set ip [lindex $argv 0 ]
set username [lindex $argv 1]
set password [lindex $argv 2 ]
set timeout 10
#set path [lindex $argv 2]
spawn ssh $username@$ip
expect {
"*yes/no" { send "yes\r"; exp_continue}
"*password:" { send "$password\r" }
}
#expect "#*"
#send "cd $path\r"
interact
